# Generated by Django 2.1.4 on 2019-01-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example',
            field=models.IntegerField(default=0),
        ),
    ]
