# Generated by Django 2.1.4 on 2019-01-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='example',
        ),
    ]
